CREATE TABLE cliente (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NULL DEFAULT NULL,
  sobrenome VARCHAR(250) NULL DEFAULT NULL,
  telefone VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (id)
 );