ALTER TABLE cliente
   ADD COLUMN cep VARCHAR(15) NULL DEFAULT NULL,
   ADD COLUMN endereco VARCHAR(250) NULL DEFAULT NULL,
   ADD COLUMN numero INT NULL DEFAULT NULL,
   ADD COLUMN bairro VARCHAR(45) NULL DEFAULT NULL,
   ADD COLUMN complemento VARCHAR(45) NULL DEFAULT NULL;